---
title: "Untitled"
author: "Kate Tran"
date: "6/6/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
# Library
```{r}
library(dplyr)
library(readr)
library(ggplot2)
library(tidyr)
library(ggpubr)
library(gridExtra)
library(grid)
library(RVAideMemoire)
library(scales)
```

# Create data
```{r}
data_wide <- read_csv("../outputs/dataset_SGM_wide_2tp.csv") 
```

# BPM
## State
```{r}
# Get adjusted p-values
plot_bpm_at10_test <- data_wide %>% 
  dplyr::select(bpm_y_scr_totalprob_t_mean, LGBT_inclusive_ever, reshist_state_so_factor_at10) %>% 
  filter(!is.na(LGBT_inclusive_ever) & !is.na(reshist_state_so_factor_at10))

p1_10 <- t.test(plot_bpm_at10_test$bpm_y_scr_totalprob_t_mean[plot_bpm_at10_test$LGBT_inclusive_ever == 0 & plot_bpm_at10_test$reshist_state_so_factor_at10 == 0],
                plot_bpm_at10_test$bpm_y_scr_totalprob_t_mean[plot_bpm_at10_test$LGBT_inclusive_ever == 0 & plot_bpm_at10_test$reshist_state_so_factor_at10 == 1])$p.value

p2_10 <- t.test(plot_bpm_at10_test$bpm_y_scr_totalprob_t_mean[plot_bpm_at10_test$LGBT_inclusive_ever == 1 & plot_bpm_at10_test$reshist_state_so_factor_at10 == 0],
                plot_bpm_at10_test$bpm_y_scr_totalprob_t_mean[plot_bpm_at10_test$LGBT_inclusive_ever == 1 & plot_bpm_at10_test$reshist_state_so_factor_at10 == 1])$p.value

p_10_adj <- round(p.adjust(c(p1_10, p2_10), method = "fdr"), 4)
```

```{r}
# Create data for plot
plot_bpm_at10 <- data_wide %>% 
  dplyr::select(bpm_y_scr_totalprob_t_mean, LGBT_inclusive_ever, reshist_state_so_factor_at10) %>% 
  filter(!is.na(LGBT_inclusive_ever) & !is.na(reshist_state_so_factor_at10)) %>% 
  group_by(LGBT_inclusive_ever, reshist_state_so_factor_at10) %>% 
  dplyr::summarize(N = n(),
                   Mean = mean(bpm_y_scr_totalprob_t_mean, na.rm=TRUE),
                   SE = (sd(bpm_y_scr_totalprob_t_mean, na.rm=TRUE))/(sqrt(N)),
                   CI = 1.96*SE) %>% 
  mutate(LGBT_inclusive_ever = recode(LGBT_inclusive_ever, `1` = "SGM", `0` = "Non-SGM"),
         reshist_state_so_factor_at10 = recode(reshist_state_so_factor_at10, `1` = "High", `0` = "Medium-Low"))

# Label for significance level
text_label_at10 <- data.frame(label = c("* * *", "*"),
                              LGBT_inclusive_ever = names(table(plot_bpm_at10$LGBT_inclusive_ever)),
                              reshist_state_so_factor_at10 = names(table(plot_bpm_at10$reshist_state_so_factor_at10)),
                              x = c(1.5, 1.5),
                              y = c(61.7, 61.7))

# Plot
plot_1 <- ggplot(plot_bpm_at10, aes(x = reshist_state_so_factor_at10, y = Mean, fill = reshist_state_so_factor_at10)) +  
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  facet_wrap(~ LGBT_inclusive_ever, nrow = 1) +
  geom_errorbar(aes(ymin = Mean - CI, ymax = Mean + CI), position = position_dodge(0.9), width = 0.2, size = 0.2) +
  xlab("") + ylab("BPM T scores (mean, 95% CI)") +
  labs(tag = "A.") +
  ggtitle("Psychopathology") +
  theme(plot.title = element_text(hjust = 0.5), panel.grid.major.x = element_blank()) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_text(size = 6),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 5.5),
        plot.title = element_text(size = 6, hjust = 0.5, colour = "black", face = "bold"),
        strip.text = element_text(size = 6, color = "dark green", face = "bold"),
        axis.ticks.x = element_blank(),
        axis.ticks = element_line(size = 0.2),
        legend.position = "top",
        legend.title = element_text(size = 6),
        legend.text = element_text(size = 6),
        aspect.ratio = 1/0.4,
        plot.tag = element_text(size = 9),
        plot.tag.position = c(0.05, 0.95)) +
  scale_fill_manual("State level indicators of bias \n  against sexual orientation", values = c("High" = "coral2", "Medium-Low" = "cyan4")) +
  geom_text(data    = text_label_at10,
            mapping = aes(x = x, y = y, label = label),
            size = 2.3, face = "bold") +
  annotate("segment", x = 1, xend = 2, y = 61.5, yend = 61.5, size = 0.22) +
  scale_y_continuous(limits=c(40, 62), oob = rescale_none)

ggsave(filename = "../plots/BMP_state.png", width = 5, height = 4, dpi = 320)
```

## Individual
```{r}
# Get adjusted p-values
p1_dim <- t.test(data_wide$bpm_y_scr_totalprob_t_mean[data_wide$LGBT_inclusive_ever == 0 & data_wide$dim_yesno_q3_ever == 0],
                 data_wide$bpm_y_scr_totalprob_t_mean[data_wide$LGBT_inclusive_ever == 0 & data_wide$dim_yesno_q3_ever == 1])$p.value

p2_dim <- t.test(data_wide$bpm_y_scr_totalprob_t_mean[data_wide$LGBT_inclusive_ever == 1 & data_wide$dim_yesno_q3_ever == 0],
                 data_wide$bpm_y_scr_totalprob_t_mean[data_wide$LGBT_inclusive_ever == 1 & data_wide$dim_yesno_q3_ever == 1])$p.value

p_dim_adj <- round(p.adjust(c(p1_dim, p2_dim), method = "fdr"), 5)
```

```{r}
# Create data for plot
plot_bpm_dim <- data_wide %>% 
  dplyr::select(bpm_y_scr_totalprob_t_mean, LGBT_inclusive_ever, dim_yesno_q3_ever) %>% 
  filter(!is.na(LGBT_inclusive_ever) & !is.na(dim_yesno_q3_ever)) %>% 
  group_by(LGBT_inclusive_ever, dim_yesno_q3_ever) %>% 
  dplyr::summarize(N = n(),
                   Mean = mean(bpm_y_scr_totalprob_t_mean, na.rm=TRUE),
                   SE = (sd(bpm_y_scr_totalprob_t_mean, na.rm=TRUE))/(sqrt(N)),
                   CI = 1.96*SE) %>% 
  mutate(LGBT_inclusive_ever = recode(LGBT_inclusive_ever, `1` = "SGM", `0` = "Non-SGM"),
         dim_yesno_q3_ever = recode(dim_yesno_q3_ever, `1` = "Yes", `0` = "No"))


# Label for significance level
text_label_dim <- data.frame(label = c("* * *", "* * *"),
                             LGBT_inclusive_ever = names(table(plot_bpm_dim$LGBT_inclusive_ever)),
                             dim_yesno_q3_ever = names(table(plot_bpm_dim$dim_yesno_q3_ever)),
                             x = c(1.5, 1.5),
                              y = c(61.7, 61.7))
  
# Plot
plot_2 <- ggplot(plot_bpm_dim, aes(x = dim_yesno_q3_ever, y = Mean, fill = dim_yesno_q3_ever)) +  
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  facet_wrap(~ LGBT_inclusive_ever, nrow = 1) +
  geom_errorbar(aes(ymin = Mean - CI, ymax = Mean + CI), position = position_dodge(0.9), width = 0.2, size = 0.2) +
  xlab("") + ylab("BPM T scores (mean, 95% CI)") +
  labs(tag = "D.") +
  ggtitle("Psychopathology") +
  theme(plot.title = element_text(hjust = 0.5), panel.grid.major.x = element_blank()) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_text(size = 6),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 5.5),
        plot.title = element_text(size = 6, hjust = 0.5, colour = "black", face = "bold"),
        strip.text = element_text(size = 6, color = "dark green", face = "bold"),
        axis.ticks.x = element_blank(),
        axis.ticks = element_line(size = 0.2),
        legend.position = "top",
        legend.title = element_text(size = 6),
        legend.text = element_text(size = 6),
        aspect.ratio = 1/0.4,
        plot.tag = element_text(size = 9),
        plot.tag.position = c(0.05, 0.95)) +
  scale_fill_manual("Individual experience of \n         discrimination \n         against SGM", values = c("Yes" = "#E6AB02", "No" = "#1B9E77")) +
  geom_text(data = text_label_dim,
            mapping = aes(x = x, y = y, label = label),
            size = 2.2, face = "bold") +
  annotate("segment", x = 1, xend = 2, y = 61.5, yend = 61.5, size = 0.2) +
  scale_y_continuous(limits=c(40, 62), oob = rescale_none)

ggsave("../plots/BMP_individual.png", width = 5, height = 4, dpi = 320)
```


# SI
## State
```{r}
p1_state_SI <- chisq.test(with(data_wide %>% filter(LGBT_inclusive_ever == 0), table(SI_y_ever, reshist_state_so_factor_at10)))$p.value
p2_state_SI <- chisq.test(with(data_wide %>% filter(LGBT_inclusive_ever == 1), table(SI_y_ever, reshist_state_so_factor_at10)))$p.value
p_state_SI_adj <- round(p.adjust(c(p1_state_SI, p2_state_SI), method = "fdr"), 5)
```

```{r}
plot_state_SI <- data_wide %>% 
  dplyr::select(SI_y_ever, LGBT_inclusive_ever, reshist_state_so_factor_at10) %>% 
  filter(!is.na(LGBT_inclusive_ever) & !is.na(reshist_state_so_factor_at10) & !is.na(SI_y_ever)) %>% 
  group_by(LGBT_inclusive_ever, reshist_state_so_factor_at10, SI_y_ever) %>% 
  summarize(sui.len = length(SI_y_ever)) %>%
  group_by(LGBT_inclusive_ever, reshist_state_so_factor_at10, SI_y_ever) %>% 
  summarize(sui.sum = sum(sui.len)) %>%
  group_by(LGBT_inclusive_ever, reshist_state_so_factor_at10) %>% 
  mutate(total = sum(sui.sum)) %>% 
  mutate(sui.prop.raw = sui.sum / sum(sui.sum),
         sui.prop = round(100* sui.prop.raw, 1)) %>% 
  filter(SI_y_ever == 1) %>% 
  rowwise() %>% 
  # add SE
  mutate(SE = 100*sqrt(sui.prop.raw*(1-sui.prop.raw)/total)) %>% 
  # add 95%CI
  mutate(CI = 1.96*SE) %>% 
  mutate(LGBT_inclusive_ever = recode(LGBT_inclusive_ever, `1` = "SGM", `0` = "Non-SGM"),
         reshist_state_so_factor_at10 = recode(reshist_state_so_factor_at10, `1` = "High", `0` = "Medium-Low"))


text_label_state_SI <- data.frame(label = c("*", "ns"),  # Create data for text
                                  LGBT_inclusive_ever = names(table(plot_state_SI$LGBT_inclusive_ever)),
                                  reshist_state_so_factor_at10 = names(table(plot_state_SI$reshist_state_so_factor_at10)),
                                  x = c(1.5, 1.5),
                                  y = c(49, 49))


plot_3 <- ggplot(plot_state_SI, aes(x = reshist_state_so_factor_at10, y = sui.prop, fill = reshist_state_so_factor_at10)) +  
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  facet_wrap(~ LGBT_inclusive_ever, nrow = 1) +
  geom_errorbar(aes(ymin = sui.prop - CI, ymax = sui.prop + CI), position = position_dodge(0.9), width = 0.2, size = 0.2) +
  xlab("") + ylab("") +
  labs(tag = "B.") +
  ggtitle("Suicide Ideation") +
  scale_y_continuous(labels = function(x) paste0(x, "%"), breaks = seq(0, 50, 10), limits = c(0,50)) +
  theme(plot.title = element_text(hjust = 0.5), panel.grid.major.x = element_blank()) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_text(size = 6),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 5),
        plot.title = element_text(size = 6, hjust = 0.5, colour = "black", face = "bold"),
        strip.text = element_text(size = 5.5, color = "dark green", face = "bold"),
        axis.ticks.x = element_blank(),
        axis.ticks=element_line(size=0.2),
        legend.position = "top",
        legend.title = element_text(size = 6),
        legend.text = element_text(size = 6),
        aspect.ratio = 1/0.4,
        plot.tag = element_text(size = 9),
        plot.tag.position = c(0.05, 0.95)) +
  scale_fill_manual("State level indicators of bias \n  against sexual orientation", values = c("High" = "coral2", "Medium-Low" = "cyan4")) +
  geom_text(data    = text_label_state_SI,
            mapping = aes(x = x, y = y, label = label),
            size = 2, face = "bold") +
  annotate("segment", x = 1, xend = 2, y = 46.8, yend = 46.8, size = 0.2)

ggsave("../plots/SI_state.png", width = 5, height = 4, dpi = 320)
```

## Individual
```{r}
p1_dim_SI <- chisq.test(with(data_wide %>% filter(LGBT_inclusive_ever == 0), table(SI_y_ever, dim_yesno_q3_ever)))$p.value
p2_dim_SI <- chisq.test(with(data_wide %>% filter(LGBT_inclusive_ever == 1), table(SI_y_ever, dim_yesno_q3_ever)))$p.value
p_dim_SI_adj <- round(p.adjust(c(p1_dim_SI, p2_dim_SI), method = "fdr"), 5)
```

```{r}
plot_dim_SI <- data_wide %>% 
  dplyr::select(SI_y_ever, LGBT_inclusive_ever, dim_yesno_q3_ever) %>% 
  filter(!is.na(LGBT_inclusive_ever) & !is.na(dim_yesno_q3_ever) & !is.na(SI_y_ever)) %>% 
  group_by(LGBT_inclusive_ever, dim_yesno_q3_ever, SI_y_ever) %>% 
  summarize(sui.len = length(SI_y_ever)) %>%
  group_by(LGBT_inclusive_ever, dim_yesno_q3_ever, SI_y_ever) %>% 
  summarize(sui.sum = sum(sui.len)) %>%
  group_by(LGBT_inclusive_ever, dim_yesno_q3_ever) %>% 
  mutate(total = sum(sui.sum)) %>% 
  mutate(sui.prop.raw = sui.sum / sum(sui.sum),
         sui.prop = round(100* sui.prop.raw, 1)) %>% 
  filter(SI_y_ever == 1) %>% 
  rowwise() %>% 
  # add SE
  mutate(SE = 100*sqrt(sui.prop.raw*(1-sui.prop.raw)/total)) %>% 
  # add 95%CI
  mutate(CI = 1.96*SE) %>% 
  mutate(LGBT_inclusive_ever = recode(LGBT_inclusive_ever, `1` = "SGM", `0` = "Non-SGM"),
         dim_yesno_q3_ever = recode(dim_yesno_q3_ever, `1` = "Yes", `0` = "No"))


text_label_dim_SI <- data.frame(label = c("* * *", "* * *"),
                                LGBT_inclusive_ever = names(table(plot_dim_SI$LGBT_inclusive_ever)),
                                dim_yesno_q3_ever = names(table(plot_dim_SI$dim_yesno_q3_ever)),
                                x = c(1.5, 1.5),
                                y = c(59, 59))

plot_4 <- ggplot(plot_dim_SI, aes(x = dim_yesno_q3_ever, y = sui.prop, fill = dim_yesno_q3_ever)) +  
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  facet_wrap(~ LGBT_inclusive_ever, nrow = 1) +
  geom_errorbar(aes(ymin = sui.prop - CI, ymax = sui.prop + CI), position = position_dodge(0.9), width = 0.2, size = 0.2) +
  xlab("") + ylab("") +
  labs(tag = "E.") +
  ggtitle("Suicide Ideation") +
  scale_y_continuous(labels = function(x) paste0(x, "%"), breaks = seq(0,60,10), limits = c(0,60)) +
  theme(plot.title = element_text(hjust = 0.5), panel.grid.major.x = element_blank()) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_text(size = 6),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 5),
        plot.title = element_text(size = 6, hjust = 0.5, colour = "black", face = "bold"),
        strip.text = element_text(size = 5.5, color = "dark green", face = "bold"),
        axis.ticks.x = element_blank(),
        axis.ticks=element_line(size=0.2),
        legend.position = "top",
        legend.title = element_text(size = 6),
        legend.text = element_text(size = 6),
        aspect.ratio = 1/0.4,
        plot.tag = element_text(size = 9),
        plot.tag.position = c(0.05, 0.95)) +
  scale_fill_manual("Individual experience of \n         discrimination \n         against SGM", values = c("Yes" = "#E6AB02", "No" = "#1B9E77")) +
  geom_text(data    = text_label_dim_SI,
            mapping = aes(x = x, y = y, label = label),
            size = 2.2,
            face = "bold") +
  annotate("segment", x = 1, xend = 2, y = 58.5, yend = 58.5, size = 0.25)

ggsave("../plots/SI_individual.png", width = 5, height = 4, dpi = 320)
```

# SA
## State
```{r}
p1_state_SA <- chisq.test(with(data_wide %>% filter(LGBT_inclusive_ever == 0), table(SA_y_ever, reshist_state_so_factor_at10)))$p.value
p2_state_SA <- chisq.test(with(data_wide %>% filter(LGBT_inclusive_ever == 1), table(SA_y_ever, reshist_state_so_factor_at10)))$p.value
p_state_SA_adj <- round(p.adjust(c(p1_state_SA, p2_state_SA), method = "fdr"), 5)
```

```{r}
plot_state_SA <- data_wide %>% 
  dplyr::select(SA_y_ever, LGBT_inclusive_ever, reshist_state_so_factor_at10) %>% 
  filter(!is.na(LGBT_inclusive_ever) & !is.na(reshist_state_so_factor_at10) & !is.na(SA_y_ever)) %>% 
  group_by(LGBT_inclusive_ever, reshist_state_so_factor_at10, SA_y_ever) %>% 
  summarize(sui.len = length(SA_y_ever)) %>%
  group_by(LGBT_inclusive_ever, reshist_state_so_factor_at10, SA_y_ever) %>% 
  summarize(sui.sum = sum(sui.len)) %>%
  group_by(LGBT_inclusive_ever, reshist_state_so_factor_at10) %>% 
  mutate(total = sum(sui.sum)) %>% 
  mutate(sui.prop.raw = sui.sum / sum(sui.sum),
         sui.prop = round(100* sui.prop.raw, 1)) %>% 
  filter(SA_y_ever == 1) %>% 
  rowwise() %>% 
  # add SE
  mutate(SE = 100*sqrt(sui.prop.raw*(1-sui.prop.raw)/total)) %>% 
  # add 95%CI
  mutate(CI = 1.96*SE) %>% 
  mutate(LGBT_inclusive_ever = recode(LGBT_inclusive_ever, `1` = "SGM", `0` = "Non-SGM"),
         reshist_state_so_factor_at10 = recode(reshist_state_so_factor_at10, `1` = "High", `0` = "Medium-Low"))


text_label_state_SA <- data.frame(label = c("ns", "ns"),
                                LGBT_inclusive_ever = names(table(plot_state_SA$LGBT_inclusive_ever)),
                                reshist_state_so_factor_at10 = names(table(plot_state_SA$reshist_state_so_factor_at10)),
                                x = c(1.5, 1.5),
                                y = c(19, 19))


plot_5 <- ggplot(plot_state_SA, aes(x = reshist_state_so_factor_at10, y = sui.prop, fill = reshist_state_so_factor_at10)) +  
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  facet_wrap(~ LGBT_inclusive_ever, nrow = 1) +
  geom_errorbar(aes(ymin = sui.prop - CI, ymax = sui.prop + CI), position = position_dodge(0.9), width = 0.2, size = 0.2) +
  xlab("") + ylab("") +
  labs(tag = "C.") +
  ggtitle("Suicide Attempt") +
  scale_y_continuous(labels = function(x) paste0(x, "%"), breaks = c(0,5,10,15,20), limits = c(0,20)) +
  theme(plot.title = element_text(hjust = 0.5), panel.grid.major.x = element_blank()) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_text(size = 6),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 5),
        plot.title = element_text(size = 5.5, hjust = 0.5, colour = "black", face = "bold"),
        strip.text = element_text(size = 5.5, color = "dark green", face = "bold"),
        axis.ticks.x = element_blank(),
        axis.ticks=element_line(size=0.2),
        legend.position = "top",
        legend.title = element_text(size = 6),
        legend.text = element_text(size = 6),
        aspect.ratio = 1/0.4,
        plot.tag = element_text(size = 9),
        plot.tag.position = c(0.05, 0.95)) +
  scale_fill_manual("State level indicators of bias \n  against sexual orientation", values = c("High" = "coral2", "Medium-Low" = "cyan4")) + 
  geom_text(data = text_label_state_SA,
            mapping = aes(x = x, y = y, label = label),
            size = 2,
            face = "bold") +
  annotate("segment", x = 1, xend = 2, y = 18.1, yend = 18.1, size = 0.2)

ggsave("../plots/SA_state.png", width = 5, height = 4, dpi = 320)
```

## Individual
```{r}
p1_dim_SA <- chisq.test(with(data_wide %>% filter(LGBT_inclusive_ever == 0), table(SA_y_ever, dim_yesno_q3_ever)))$p.value
p2_dim_SA <- chisq.test(with(data_wide %>% filter(LGBT_inclusive_ever == 1), table(SA_y_ever, dim_yesno_q3_ever)))$p.value
p_dim_SA_adj <- round(p.adjust(c(p1_dim_SA, p2_dim_SA), method = "fdr"), 5)
```

```{r}
plot_dim_SA <- data_wide %>% 
  dplyr::select(SA_y_ever, LGBT_inclusive_ever, dim_yesno_q3_ever) %>% 
  filter(!is.na(LGBT_inclusive_ever) & !is.na(dim_yesno_q3_ever) & !is.na(SA_y_ever)) %>% 
  group_by(LGBT_inclusive_ever, dim_yesno_q3_ever, SA_y_ever) %>% 
  summarize(sui.len = length(SA_y_ever)) %>%
  group_by(LGBT_inclusive_ever, dim_yesno_q3_ever, SA_y_ever) %>% 
  summarize(sui.sum = sum(sui.len)) %>%
  group_by(LGBT_inclusive_ever, dim_yesno_q3_ever) %>% 
  mutate(total = sum(sui.sum)) %>% 
  mutate(sui.prop.raw = sui.sum / sum(sui.sum),
         sui.prop = round(100* sui.prop.raw, 1)) %>% 
  filter(SA_y_ever == 1) %>% 
  rowwise() %>% 
  # add SE
  mutate(SE = 100*sqrt(sui.prop.raw*(1-sui.prop.raw)/total)) %>% 
  # add 95%CI
  mutate(CI = 1.96*SE) %>% 
  mutate(LGBT_inclusive_ever = recode(LGBT_inclusive_ever, `1` = "SGM", `0` = "Non-SGM"),
         dim_yesno_q3_ever = recode(dim_yesno_q3_ever, `1` = "Yes", `0` = "No"))


text_label_dim_SA <- data.frame(label = c("* * *", "* * *"),
                                  LGBT_inclusive_ever = names(table(plot_dim_SA$LGBT_inclusive_ever)),
                                  dim_yesno_q3_ever = names(table(plot_dim_SA$dim_yesno_q3_ever)),
                                  x = c(1.5, 1.5),
                                  y = c(19, 19))


plot_6 <- ggplot(plot_dim_SA, aes(x = dim_yesno_q3_ever, y = sui.prop, fill = dim_yesno_q3_ever)) +  
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  facet_wrap(~ LGBT_inclusive_ever, nrow = 1) +
  geom_errorbar(aes(ymin = sui.prop - CI, ymax = sui.prop + CI), position = position_dodge(0.9), width = 0.2, size = 0.2) +
  xlab("") + ylab("") +
  labs(tag = "F.") +
  ggtitle("Suicide Attempt") +
  scale_y_continuous(labels = function(x) paste0(x, "%"), breaks = c(0,5,10,15,20), limits = c(0,20)) +
  theme(plot.title = element_text(hjust = 0.5), panel.grid.major.x = element_blank()) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_text(size = 6),
        axis.title.y = element_text(size = 5),
        axis.title.x = element_blank(),
        plot.title = element_text(size = 5.5, hjust = 0.5, colour = "black", face = "bold"),
        strip.text = element_text(size = 5.5, color = "dark green", face = "bold"),
        axis.ticks.x = element_blank(),
        axis.ticks=element_line(size=0.2),
        legend.position = "top",
        legend.title = element_text(size = 6),
        legend.text = element_text(size = 6),
        aspect.ratio = 1/0.4,
        plot.tag = element_text(size = 9),
        plot.tag.position = c(0.05, 0.95)) +
  scale_fill_manual("Individual experience of \n         discrimination \n         against SGM", values = c("Yes" = "#E6AB02", "No" = "#1B9E77")) +
  geom_text(data    = text_label_dim_SA,
            mapping = aes(x = x, y = y, label = label),
            size = 2.2,
            face = "bold") +
  annotate("segment", x = 1, xend = 2, y = 18.6, yend = 18.6, size = 0.2)

ggsave("../plots/SA_individual.png", width = 5, height = 4, dpi = 320)
```

# Merge plots
```{r}
# BPM, SI, SA state bias
ggarrange(
  plot_1 +
    theme(plot.margin = margin(r = 1, l = 1)),
  NULL,
  plot_3 + 
    theme(plot.margin = margin(r = 1, l = 1)), 
  NULL,
  plot_5 + 
    theme(plot.margin = margin(l = 1),
    ), 
  nrow = 1,
  widths = c(1, 0.05, 1, 0.05, 1),
  heights = c(5,5,5,5,5),
  common.legend = T,
  legend = "right")

ggsave("../plots/interaction_plots_state_main.png", width = 5, height = 3, dpi = 320)


# BPM, SI, SA individual discrimination
ggarrange(
  plot_2 +
    theme(plot.margin = margin(r = 1, l = 1)),
  NULL,
  plot_4 + 
    theme(plot.margin = margin(r = 1, l = 1)), 
  NULL,
  plot_6 + 
    theme(plot.margin = margin(l = 1),
    ), 
  nrow = 1,
  widths = c(1, 0.05, 1, 0.05, 1),
  heights = c(5,5,5,5,5),
  common.legend = T,
  legend = "right")

ggsave("../plots/interaction_plots_individual_main.png", width = 5, height = 2, dpi = 320)
```


# Supplement
# CBCL
## Individual
```{r}
p1_dim_cbcl <- t.test(data_wide$cbcl_scr_syn_totprob_t_mean[data_wide$LGBT_inclusive_ever == 0 & data_wide$dim_yesno_q3_ever == 0],
                 data_wide$cbcl_scr_syn_totprob_t_mean[data_wide$LGBT_inclusive_ever == 0 & data_wide$dim_yesno_q3_ever == 1])$p.value

p2_dim_cbcl <- t.test(data_wide$cbcl_scr_syn_totprob_t_mean[data_wide$LGBT_inclusive_ever == 1 & data_wide$dim_yesno_q3_ever == 0],
                 data_wide$cbcl_scr_syn_totprob_t_mean[data_wide$LGBT_inclusive_ever == 1 & data_wide$dim_yesno_q3_ever == 1])$p.value

p_dim_cbcl_adj <- round(p.adjust(c(p1_dim_cbcl, p2_dim_cbcl), method = "fdr"), 5)
```

```{r}
plot_dim_cbcl <- data_wide %>% 
  dplyr::select(cbcl_scr_syn_totprob_t_mean, LGBT_inclusive_ever, dim_yesno_q3_ever) %>% 
  filter(!is.na(LGBT_inclusive_ever) & !is.na(dim_yesno_q3_ever)) %>% 
  group_by(LGBT_inclusive_ever, dim_yesno_q3_ever) %>% 
  dplyr::summarize(N = n(),
                   Mean = mean(cbcl_scr_syn_totprob_t_mean, na.rm=TRUE),
                   SE = (sd(cbcl_scr_syn_totprob_t_mean, na.rm=TRUE))/(sqrt(N)),
                   CI = 1.96*SE) %>% 
  mutate(LGBT_inclusive_ever = recode(LGBT_inclusive_ever, `1` = "SGM", `0` = "Non-SGM"),
         dim_yesno_q3_ever = recode(dim_yesno_q3_ever, `1` = "Yes", `0` = "No"))


text_label_dim_cbcl <- data.frame(label = c("* * *", "* * *"),
                             LGBT_inclusive_ever = names(table(plot_dim_cbcl$LGBT_inclusive_ever)),
                             dim_yesno_q3_ever = names(table(plot_dim_cbcl$dim_yesno_q3_ever)),
                             x = c(1.5, 1.5),
                              y = c(55.7, 55.7))


plot_7 <- ggplot(plot_dim_cbcl, aes(x = dim_yesno_q3_ever, y = Mean, fill = dim_yesno_q3_ever)) +  
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  facet_wrap(~ LGBT_inclusive_ever, nrow = 1) +
  geom_errorbar(aes(ymin = Mean - CI, ymax = Mean + CI), position = position_dodge(0.9), width = 0.2, size = 0.2) +
  xlab("") + ylab("CBCL T scores (mean, 95% CI)") +
  labs(tag = "A.") +
  ggtitle("") +
  theme(plot.title = element_text(hjust = 0.5), panel.grid.major.x = element_blank()) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_text(size = 8),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 7),
        plot.title = element_text(size = 8, hjust = 0.5, colour = "black"),
        strip.text = element_text(size = 7.5, color = "dark green", face = "bold"),
        axis.ticks.x = element_blank(),
        legend.position = "bottom",
        legend.title = element_text(size = 8),
        legend.text = element_text(size = 8),
        aspect.ratio = 1/0.4,
        plot.tag = element_text(),
        plot.tag.position = c(0.05, 0.95)) +
  scale_fill_manual("Individual experience of \n         discrimination \n         against SGM", values = c("Yes" = "#E6AB02", "No" = "#1B9E77")) +
  geom_text(data    = text_label_dim_cbcl,
            mapping = aes(x = x, y = y, label = label),
            size = 3,
            face = "bold") +
  annotate("segment", x = 1, xend = 2, y = 55.5, yend = 55.5, size = 0.2) +
  scale_y_continuous(limits=c(40, 56), oob = rescale_none)

ggsave("../plots/CBCL_individual.png", width = 5, height = 4, dpi = 320)
```

## State
```{r}
p1_cbcl <- t.test(data_wide$cbcl_scr_syn_totprob_t_mean[data_wide$LGBT_inclusive_ever == 0 & data_wide$reshist_state_so_factor_at10 == 0],
                  data_wide$cbcl_scr_syn_totprob_t_mean[data_wide$LGBT_inclusive_ever == 0 & data_wide$reshist_state_so_factor_at10 == 1])$p.value

p2_cbcl <- t.test(data_wide$cbcl_scr_syn_totprob_t_mean[data_wide$LGBT_inclusive_ever == 1 & data_wide$reshist_state_so_factor_at10 == 0],
                  data_wide$cbcl_scr_syn_totprob_t_mean[data_wide$LGBT_inclusive_ever == 1 & data_wide$reshist_state_so_factor_at10 == 1])$p.value

p_cbcl_adj <- round(p.adjust(c(p1_cbcl, p2_cbcl), method = "fdr"), 5)
```


```{r}
plot_cbcl_at10 <- data_wide %>% 
  dplyr::select(cbcl_scr_syn_totprob_t_mean, LGBT_inclusive_ever, reshist_state_so_factor_at10) %>% 
  filter(!is.na(LGBT_inclusive_ever) & !is.na(reshist_state_so_factor_at10)) %>% 
  group_by(LGBT_inclusive_ever, reshist_state_so_factor_at10) %>% 
  dplyr::summarize(N = n(),
                   Mean = mean(cbcl_scr_syn_totprob_t_mean, na.rm=TRUE),
                   SE = (sd(cbcl_scr_syn_totprob_t_mean, na.rm=TRUE))/(sqrt(N)),
                   CI = 1.96*SE) %>% 
  mutate(LGBT_inclusive_ever = recode(LGBT_inclusive_ever, `1` = "SGM", `0` = "Non-SGM"),
         reshist_state_so_factor_at10 = recode(reshist_state_so_factor_at10, `1` = "High", `0` = "Medium-Low"))


text_label_at10_cbcl <- data.frame(label = c("* * *", "*"),
                                   LGBT_inclusive_ever = names(table(plot_cbcl_at10$LGBT_inclusive_ever)),
                                   reshist_state_so_factor_at10 = names(table(plot_cbcl_at10$reshist_state_so_factor_at10)),
                                   x = c(1.5, 1.5),
                              y = c(55.7, 55.7))


plot_8 <- ggplot(plot_cbcl_at10, aes(x = reshist_state_so_factor_at10, y = Mean, fill = reshist_state_so_factor_at10)) +  
  geom_bar(stat = "identity", position = position_dodge(width = 0.9)) +
  facet_wrap(~ LGBT_inclusive_ever, nrow = 1) +
  geom_errorbar(aes(ymin = Mean - CI, ymax = Mean + CI), position = position_dodge(0.9), width = 0.2, size = 0.2) +
  xlab("") + ylab("CBCL T scores (mean, 95% CI)") +
  labs(tag = "B.") +
  ggtitle("") +
  theme(plot.title = element_text(hjust = 0.5), panel.grid.major.x = element_blank()) +
  theme(axis.text.x = element_blank(),
        axis.text.y = element_text(size = 8),
        axis.title.x = element_blank(),
        axis.title.y = element_text(size = 7),
        plot.title = element_text(size = 8, hjust = 0.5, colour = "black"),
        strip.text = element_text(size = 7.5, color = "dark green", face = "bold"),
        axis.ticks.x = element_blank(),
        legend.position = "bottom",
        legend.title = element_text(size = 8),
        legend.text = element_text(size = 8),
        aspect.ratio = 1/0.4,
        plot.tag = element_text(),
        plot.tag.position = c(0.05, 0.95)) +
  scale_fill_manual("State level indicators of bias \n  against sexual orientation", values = c("High" = "coral2", "Medium-Low" = "cyan4")) +
  geom_text(data    = text_label_at10_cbcl,
            mapping = aes(x = x, y = y, label = label),
            size = 3,
            face = "bold") +
  annotate("segment", x = 1, xend = 2, y = 55.5, yend = 55.5, size = 0.2) +
  scale_y_continuous(limits=c(40, 56), oob = rescale_none)

ggsave("../plots/CBCL_state.png", width = 5, height = 4, dpi = 320)
```