---
title: "Untitled"
author: "Kate Tran"
date: "6/7/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
library(dplyr)
library(tidyr)
library(stats)
library(readxl)
library(jstable)
```

# Read data
```{r}
dataset_wide <- read.csv("../outputs/dataset_SGM_wide_3tp.csv")
```

# Ever: at any of 3 time points (baseline, 1y and 2y)
```{r}
dataset_wide$LGBT_inclusive_ever <- apply(dataset_wide[,grepl("LGBT_inclusive_", colnames(dataset_wide))],1 ,function(x) {any(x == 1)*1})
dataset_wide$LGBT_inclusive_ever <- ifelse( (is.na(dataset_wide$LGBT_inclusive_ever) & 
                                                     (apply(dataset_wide[,which(grepl("LGBT_inclusive_", colnames(dataset_wide)))], 1, function(x) {any(x == 0)}))), 
                                                  0, dataset_wide$LGBT_inclusive_ever)

dataset_wide$dim_yesno_q1_ever <- apply(dataset_wide[,grepl("dim_yesno_q1_", colnames(dataset_wide))],1 ,function(x) {any(x == 1)*1})
dataset_wide$dim_yesno_q1_ever <- ifelse((is.na(dataset_wide$dim_yesno_q1_ever) & 
                                           (apply(dataset_wide[,which(grepl("dim_yesno_q1_", colnames(dataset_wide)))], 1, function(x) {any(x == 0)}))), 
                                        0, dataset_wide$dim_yesno_q1_ever)


dataset_wide$dim_yesno_q2_ever <- apply(dataset_wide[,grepl("dim_yesno_q2_", colnames(dataset_wide))],1 ,function(x) {any(x == 1)*1})
dataset_wide$dim_yesno_q2_ever <- ifelse((is.na(dataset_wide$dim_yesno_q2_ever) & 
                                           (apply(dataset_wide[,which(grepl("dim_yesno_q2_", colnames(dataset_wide)))], 1, function(x) {any(x == 0)}))), 
                                        0, dataset_wide$dim_yesno_q2_ever)

dataset_wide$dim_yesno_q3_ever <- apply(dataset_wide[,grepl("dim_yesno_q3_", colnames(dataset_wide))],1 ,function(x) {any(x == 1)*1})
dataset_wide$dim_yesno_q3_ever <- ifelse((is.na(dataset_wide$dim_yesno_q3_ever) & 
                                                     (apply(dataset_wide[,which(grepl("dim_yesno_q3_", colnames(dataset_wide)))], 1, function(x) {any(x == 0)}))), 
                                                  0, dataset_wide$dim_yesno_q3_ever)

dataset_wide$dim_yesno_q4_ever <- apply(dataset_wide[,grepl("dim_yesno_q4_", colnames(dataset_wide))],1 ,function(x) {any(x == 1)*1})
dataset_wide$dim_yesno_q4_ever <- ifelse((is.na(dataset_wide$dim_yesno_q4_ever) & 
                                           (apply(dataset_wide[,which(grepl("dim_yesno_q4_", colnames(dataset_wide)))], 1, function(x) {any(x == 0)}))), 
                                        0, dataset_wide$dim_yesno_q4_ever)


dataset_wide$suicidality_y_ever <- apply(dataset_wide[,grepl("suicidality_y", colnames(dataset_wide))],1 ,function(x) {any(x == 1)*1})
dataset_wide$SA_y_ever <- apply(dataset_wide[,grepl("SA_y", colnames(dataset_wide))],1 ,function(x) {any(x == 1)*1})
dataset_wide$SI_y_ever <- apply(dataset_wide[,grepl("SI_y", colnames(dataset_wide))],1 ,function(x) {any(x == 1)*1})
```

```{r}
# Diagnosis, symptom
# bpm_y_scr_totalprob_r, bpm_y_scr_totalprob_t, cbcl_scr_syn_totprob_r, cbcl_scr_syn_totprob_t: mean
dataset_wide$bpm_y_scr_totalprob_r_mean <- rowMeans(dataset_wide[,which(grepl("bpm_y_scr_totalprob_r", colnames(dataset_wide)))], na.rm = T)
dataset_wide$bpm_y_scr_totalprob_t_mean <- rowMeans(dataset_wide[,which(grepl("bpm_y_scr_totalprob_t", colnames(dataset_wide)))], na.rm = T)
dataset_wide$cbcl_scr_syn_totprob_r_mean <- rowMeans(dataset_wide[,which(grepl("cbcl_scr_syn_totprob_r", colnames(dataset_wide)))], na.rm = T)
dataset_wide$cbcl_scr_syn_totprob_t_mean <- rowMeans(dataset_wide[,which(grepl("cbcl_scr_syn_totprob_t", colnames(dataset_wide)))], na.rm = T)


dataset_wide$ksads_ODD_Diagnosis_ever <- apply(dataset_wide[,grepl("ksads_ODD_Diagnosis", colnames(dataset_wide))],1 ,function(x) {any(x == 1)*1})
dataset_wide$ksads_ODD_Diagnosis_ever <- ifelse((is.na(dataset_wide$ksads_ODD_Diagnosis_ever) & 
                                                  (apply(dataset_wide[,which(grepl("ksads_ODD_Diagnosis", colnames(dataset_wide)))], 1, function(x) {any(x == 0)}))), 
                                               0, dataset_wide$ksads_ODD_Diagnosis_ever)

dataset_wide$ksads_CONDUCT_Diagnosis_ever <- apply(dataset_wide[,grepl("ksads_CONDUCT_Diagnosis", colnames(dataset_wide))],1 ,function(x) {any(x == 1)*1})
dataset_wide$ksads_CONDUCT_Diagnosis_ever <- ifelse((is.na(dataset_wide$ksads_CONDUCT_Diagnosis_ever) & 
                                                      (apply(dataset_wide[,which(grepl("ksads_CONDUCT_Diagnosis", colnames(dataset_wide)))], 1, function(x) {any(x == 0)}))), 
                                                   0, dataset_wide$ksads_CONDUCT_Diagnosis_ever)

dataset_wide$ksads_any_externalizing_diagnosis_ever <- apply(dataset_wide[,grepl("ksads_any_externalizing_diagnosis", colnames(dataset_wide))],1 ,function(x) {any(x == 1)*1})
dataset_wide$ksads_any_externalizing_diagnosis_ever <- ifelse((is.na(dataset_wide$ksads_any_externalizing_diagnosis_ever) & 
                                                                (apply(dataset_wide[,which(grepl("ksads_any_externalizing_diagnosis", colnames(dataset_wide)))], 1, function(x) {any(x == 0)}))), 
                                                             0, dataset_wide$ksads_any_externalizing_diagnosis_ever)

dataset_wide$ksads_PTSD_diagnosis_ever <- apply(dataset_wide[,grepl("ksads_PTSD_diagnosis", colnames(dataset_wide))],1 ,function(x) {any(x == 1)*1})
dataset_wide$ksads_PTSD_diagnosis_ever <- ifelse((is.na(dataset_wide$ksads_PTSD_diagnosis_ever) & 
                                                   (apply(dataset_wide[,which(grepl("ksads_PTSD_diagnosis", colnames(dataset_wide)))], 1, function(x) {any(x == 0)}))), 
                                                0, dataset_wide$ksads_PTSD_diagnosis_ever)

dataset_wide$ksads_trauma_diagnosis_ever <- apply(dataset_wide[,grepl("ksads_trauma_diagnosis", colnames(dataset_wide))],1 ,function(x) {any(x == 1)*1})
dataset_wide$ksads_trauma_diagnosis_ever <- ifelse((is.na(dataset_wide$ksads_trauma_diagnosis_ever) & 
                                                     (apply(dataset_wide[,which(grepl("ksads_trauma_diagnosis", colnames(dataset_wide)))], 1, function(x) {any(x == 0)}))), 
                                                  0, dataset_wide$ksads_trauma_diagnosis_ever)

dataset_wide$ksads_any_trauma_diagnosis_ever <- apply(dataset_wide[,grepl("ksads_any_trauma_diagnosis", colnames(dataset_wide))],1 ,function(x) {any(x == 1)*1})
dataset_wide$ksads_any_trauma_diagnosis_ever <- ifelse((is.na(dataset_wide$ksads_any_trauma_diagnosis_ever) & 
                                                         (apply(dataset_wide[,which(grepl("ksads_any_trauma_diagnosis", colnames(dataset_wide)))], 1, function(x) {any(x == 0)}))), 
                                                      0, dataset_wide$ksads_any_trauma_diagnosis_ever)

dataset_wide$diagnosis_bipolar_y_ever <- apply(dataset_wide[,grepl("diagnosis_bipolar_y", colnames(dataset_wide))],1 ,function(x) {any(x == 1)*1})
dataset_wide$diagnosis_bipolar_y_ever <- ifelse((is.na(dataset_wide$diagnosis_bipolar_y_ever) & 
                                                  (apply(dataset_wide[,which(grepl("diagnosis_bipolar_y", colnames(dataset_wide)))], 1, function(x) {any(x == 0)}))), 
                                               0, dataset_wide$diagnosis_bipolar_y_ever)

dataset_wide$diagnosis_anxiety_y_ever <- apply(dataset_wide[,grepl("diagnosis_anxiety_y", colnames(dataset_wide))],1 ,function(x) {any(x == 1)*1})
dataset_wide$diagnosis_anxiety_y_ever <- ifelse((is.na(dataset_wide$diagnosis_anxiety_y_ever) & 
                                                  (apply(dataset_wide[,which(grepl("diagnosis_anxiety_y", colnames(dataset_wide)))], 1, function(x) {any(x == 0)}))), 
                                               0, dataset_wide$diagnosis_anxiety_y_ever)

dataset_wide$ksads_ADHD_Diagnosis_ever <- apply(dataset_wide[,grepl("ksads_ADHD_Diagnosis", colnames(dataset_wide))],1 ,function(x) {any(x == 1)*1})
dataset_wide$ksads_ADHD_Diagnosis_ever <- ifelse((is.na(dataset_wide$ksads_ADHD_Diagnosis_ever) & 
                                                   (apply(dataset_wide[,which(grepl("ksads_ADHD_Diagnosis", colnames(dataset_wide)))], 1, function(x) {any(x == 0)}))), 
                                                0, dataset_wide$ksads_ADHD_Diagnosis_ever)

dataset_wide$diagnosis_depression_y_ever <- apply(dataset_wide[,grepl("diagnosis_depression_y", colnames(dataset_wide))],1 ,function(x) {any(x == 1)*1})
dataset_wide$diagnosis_depression_y_ever <- ifelse((is.na(dataset_wide$diagnosis_depression_y_ever) & 
                                                     (apply(dataset_wide[,which(grepl("diagnosis_depression_y", colnames(dataset_wide)))], 1, function(x) {any(x == 0)}))), 
                                                  0, dataset_wide$diagnosis_depression_y_ever)

dataset_wide$diagnosis_ocd_y_ever <- apply(dataset_wide[,grepl("diagnosis_ocd_y", colnames(dataset_wide))],1 ,function(x) {any(x == 1)*1})
dataset_wide$diagnosis_ocd_y_ever <- ifelse((is.na(dataset_wide$diagnosis_ocd_y_ever) & 
                                              (apply(dataset_wide[,which(grepl("diagnosis_ocd_y", colnames(dataset_wide)))], 1, function(x) {any(x == 0)}))), 
                                           0, dataset_wide$diagnosis_ocd_y_ever)

dataset_wide$diagnosis_ptsd_y_ever <- apply(dataset_wide[,grepl("diagnosis_ptsd_y", colnames(dataset_wide))],1 ,function(x) {any(x == 1)*1})
dataset_wide$diagnosis_ptsd_y_ever <- ifelse((is.na(dataset_wide$diagnosis_ptsd_y_ever) & 
                                               (apply(dataset_wide[,which(grepl("diagnosis_ptsd_y", colnames(dataset_wide)))], 1, function(x) {any(x == 0)}))), 
                                            0, dataset_wide$diagnosis_ptsd_y_ever)

dataset_wide$ksads_ADHD_symptoms_sum_mean <- rowMeans(dataset_wide[,which(grepl("ksads_ADHD_symptoms_sum", colnames(dataset_wide)))], na.rm = T)
dataset_wide$ksads_ADHD_exclude_attention_symptoms_sum_mean <- 
  rowMeans(dataset_wide[,which(grepl("ksads_ADHD_exclude_attention_symptoms_sum", colnames(dataset_wide)))], na.rm = T)
dataset_wide$ksads_ODD_symptoms_sum_mean <- rowMeans(dataset_wide[,which(grepl("ksads_ODD_symptoms_sum", colnames(dataset_wide)))], na.rm = T)
dataset_wide$ksads_CONDUCT_symptoms_sum_mean <- rowMeans(dataset_wide[,which(grepl("ksads_CONDUCT_symptoms_sum", colnames(dataset_wide)))], na.rm = T)
dataset_wide$ksads_externalizing_symptoms_sum_mean <- rowMeans(dataset_wide[,which(grepl("ksads_externalizing_symptoms_sum", colnames(dataset_wide)))], na.rm = T)
dataset_wide$ksads_externalizing_exclude_attentation_symptoms_sum_mean <- 
  rowMeans(dataset_wide[,which(grepl("ksads_externalizing_exclude_attentation_symptoms_sum", colnames(dataset_wide)))], na.rm = T)

dataset_wide$ksads_ptsd_symptoms_summary_mean <- rowMeans(dataset_wide[,which(grepl("ksads_ptsd_symptoms_summary", colnames(dataset_wide)))], na.rm = T)

```

# Table 1
```{r}
# Main table 1
vars_main <- dataset_wide %>% 
  dplyr::select(
    age_year_2y,
    sex_br,
    race_white,
    race_black,
    race_aian,
    race_nhpi,
    race_asian,
    race_other,
    race_mixed,
    ethnicity_hisp,
    household_income_2y,
    dim_yesno_q3_ever,
    reshist_state_so_factor,
    dim_yesno_q1_ever,
    dim_yesno_q2_ever,
    dim_yesno_q4_ever,
    cybb_phenx_harm_2y,
    peq_ss_relational_victim_2y,
    peq_ss_reputation_victim_2y,
    peq_ss_overt_victim_2y,
    reshist_addr1_adi_wsum,
    bpm_y_scr_totalprob_t_mean,
    cbcl_scr_syn_totprob_t_mean,
    SA_y_ever,
    SI_y_ever) %>% names()

write.csv(print(
  CreateTableOne2(
    data = dataset_wide,
    vars = vars_main,
    strata = "LGBT_inclusive_ever",
    factorVars = c(
      "sex_br",
      "race_white",
      "race_black",
      "race_aian",
      "race_nhpi",
      "race_asian",
      "race_other",
      "race_mixed",
      "ethnicity_hisp",
      "dim_yesno_q1_ever",
      "dim_yesno_q2_ever",
      "dim_yesno_q3_ever",
      "dim_yesno_q4_ever",
      "cybb_phenx_harm_2y",
      "suicidality_y_ever",
       "SI_y_ever",
      "SA_y_ever"
    ),
    pDigits = 5,
    includeNA = T
  )
),
"../outputs/table1_main_071922.csv")

# Total
write.csv(print(
tableone::CreateTableOne(
    data = dataset_wide,
    vars = vars_main,
    strata = "LGBT_inclusive_ever",
    addOverall = T,
    includeNA = T,
    factorVars = c(
      "sex_br",
      "race_white",
      "race_black",
      "race_aian",
      "race_nhpi",
      "race_asian",
      "race_other",
      "race_mixed",
      "ethnicity_hisp",
      "dim_yesno_q1_ever",
      "dim_yesno_q2_ever",
      "dim_yesno_q3_ever",
      "dim_yesno_q4_ever",
      "cybb_phenx_harm_2y",
      "suicidality_y_ever",
       "SI_y_ever",
      "SA_y_ever"
    )
), 
missing = T,
pDigits = 7
),
"../outputs/table1_main_total_071922.csv")

# Missing values
write.csv(print(questionr::freq.na(data = dataset_wide, vars_main)), "../outputs/table1_main_missing_071922.csv")
```

# Adjusted p-values
```{r}
# Calculate adjusted p-values
# Sheet 2: p-values from CreateTableOne2

p_values <- "../outputs/table1_main_071922.xlsx" %>% read_excel(sheet = 2)

p_values <- p_values %>%
  mutate(adj_p = round(p.adjust(p, method = "fdr", ), 3))

writexl::write_xlsx(p_values, "../outputs/table1_main_adjp_071922.xlsx")
```

```{r}
# Supplement table 1
vars_supp <- dataset_wide %>%
  dplyr::select(
    ksads_ODD_Diagnosis_ever,
    ksads_CONDUCT_Diagnosis_ever,
    ksads_any_externalizing_diagnosis_ever,
    ksads_PTSD_diagnosis_ever,
    ksads_trauma_diagnosis_ever,
    ksads_any_trauma_diagnosis_ever,
    diagnosis_bipolar_y_ever,
    diagnosis_anxiety_y_ever,
    diagnosis_depression_y_ever,
    ksads_ADHD_symptoms_sum_mean,
    ksads_ADHD_exclude_attention_symptoms_sum_mean,
    ksads_ODD_symptoms_sum_mean,
    ksads_CONDUCT_symptoms_sum_mean,
    ksads_externalizing_symptoms_sum_mean,
    ksads_externalizing_exclude_attentation_symptoms_sum_mean,
    ksads_ptsd_symptoms_summary_mean,
    suicidality_y_ever,
    bpm_y_scr_totalprob_r_mean,
    cbcl_scr_syn_totprob_r_mean
  ) %>% names()

write.csv(print(
  CreateTableOne2(
    data = dataset_wide,
    vars = vars_supp,
    strata = "LGBT_inclusive_ever",
    factorVars = c(
      "ksads_ODD_Diagnosis_ever",
      "ksads_CONDUCT_Diagnosis_ever",
      "ksads_any_externalizing_diagnosis_ever",
      "ksads_PTSD_diagnosis_ever",
      "ksads_trauma_diagnosis_ever",
      "ksads_any_trauma_diagnosis_ever",
      "diagnosis_bipolar_y_ever",
      "diagnosis_anxiety_y_ever",
      "diagnosis_depression_y_ever",
      "suicidality_y_ever"
    ),
    pDigits = 5,
    includeNA = T
  )
),
"../outputs/table1_supp_071922.csv")
```

```{r}
# Sheet 2: p-values from CreateTableOne2
p_values_supp <- "../outputs/table1_supp_071922.xlsx" %>% read_excel(sheet = 2)

p_values_supp <- p_values_supp %>%
  mutate(adj_p = round(p.adjust(p, method = "fdr", ), 3))

writexl::write_xlsx(p_values_supp, "../outputs/table1_supp_adjp_071922.xlsx")
```

















