---
title: "Untitled"
author: "Kate Tran"
date: "5/4/2022"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Library
```{r}
library(dplyr)
library(readr)
library(gtsummary)
library(sjPlot)
library(lme4)
library(ggplot2)
library(tidyr)
library(modelr)
library(optimx)
library(qgraph)
```

```{r}
dataset_long <- read_csv("../outputs/dataset_SGM_long_mm.csv")
```

# MAIN ANALYSIS
## BPM
```{r}
# Main models
bpm_mod_1 <- lmer(bpm_y_scr_totalprob_t ~ LGBT_inclusive + scale(age_year) + (scale(age_year)^2) + sex_br + race_white + 
                    race_black + ethnicity_hisp + scale(income_resid) +
                    (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long)

bpm_mod_2 <- lmer(bpm_y_scr_totalprob_t ~ LGBT_inclusive + dim_yesno_q3 + scale(reshist_state_so_factor) + scale(age_year) + (scale(age_year)^2) + sex_br + race_white + 
                    race_black + ethnicity_hisp + scale(income_resid) +
                    (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long)

bpm_mod_3 <- lmer(bpm_y_scr_totalprob_t ~ LGBT_inclusive + dim_yesno_q3 + scale(reshist_state_so_factor) + scale(age_year) + (scale(age_year)^2) + sex_br + race_white +
                    race_black + ethnicity_hisp + scale(income_resid) +
                    dim_yesno_q1 + dim_yesno_q2 + dim_yesno_q4 + cybb_phenx_harm + bully_vic + reshist_addr1_adi_perc +
                                           (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long,
                  control=lmerControl(check.nobs.vs.nlev = "ignore",
                                      check.nobs.vs.rankZ = "ignore",
                                      check.nobs.vs.nRE="ignore",
                                      optimizer = "bobyqa", optCtrl = list(maxfun = 2e5)))

bpm_mod_4 <- lmer(bpm_y_scr_totalprob_t ~ LGBT_inclusive + dim_yesno_q3 + scale(reshist_state_so_factor) + scale(age_year) + (scale(age_year)^2) + sex_br + race_white +
                    race_black + ethnicity_hisp + scale(income_resid) +
                    dim_yesno_q1 + dim_yesno_q2 + dim_yesno_q4 + cybb_phenx_harm + bully_vic +
                    dim_yesno_q3*LGBT_inclusive + dim_yesno_q3*scale(reshist_state_so_factor) + scale(reshist_state_so_factor)*LGBT_inclusive + reshist_addr1_adi_perc +
                    (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long,
                  control=lmerControl(check.nobs.vs.nlev = "ignore",
                                      check.nobs.vs.rankZ = "ignore",
                                      check.nobs.vs.nRE="ignore",
                                      optimizer = "bobyqa", optCtrl = list(maxfun = 2e5)))

bpm_comb <- tab_model(bpm_mod_1, bpm_mod_2, bpm_mod_3, bpm_mod_4, show.intercept = F) #
bpm_comb
```

## Suicide ideation
```{r}
SI_mod_1 <- glmer(SI_y ~ LGBT_inclusive + scale(age_year) + (scale(age_year)^2) + sex_br + race_white + 
                    race_black + ethnicity_hisp + scale(income_resid) +
                    (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long, family = binomial, nAGQ = 0)


SI_mod_2 <- glmer(SI_y ~ LGBT_inclusive + dim_yesno_q3 + scale(reshist_state_so_factor) + scale(age_year) + (scale(age_year)^2) + sex_br + race_white + 
                    race_black + ethnicity_hisp + scale(income_resid) +
                    (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long, family = binomial, nAGQ = 0)


SI_mod_3 <- glmer(SI_y ~ LGBT_inclusive + dim_yesno_q3 + scale(reshist_state_so_factor) + scale(age_year) + (scale(age_year)^2) + sex_br + race_white +
                    race_black + ethnicity_hisp + scale(income_resid) +
                    dim_yesno_q1 + dim_yesno_q2 + dim_yesno_q4 + cybb_phenx_harm + bully_vic + reshist_addr1_adi_perc +
                                           (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long, family = binomial, nAGQ = 0)

SI_mod_4 <- glmer(SI_y ~ LGBT_inclusive + dim_yesno_q3 + scale(reshist_state_so_factor) + scale(age_year) + (scale(age_year)^2) + sex_br + race_white +
                    race_black + ethnicity_hisp + scale(income_resid) +
                    dim_yesno_q1 + dim_yesno_q2 + dim_yesno_q4 + cybb_phenx_harm + bully_vic +
                    dim_yesno_q3*LGBT_inclusive + dim_yesno_q3*scale(reshist_state_so_factor) + scale(reshist_state_so_factor)*LGBT_inclusive + reshist_addr1_adi_perc +
                    (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long, family = binomial, nAGQ = 0)


SI_comb <- tab_model(SI_mod_1, SI_mod_2, SI_mod_3, SI_mod_4, show.intercept = F)
SI_comb
```

## Suicide attempt
```{r}
SA_mod_1 <- glmer(SA_y ~ LGBT_inclusive + scale(age_year) + (scale(age_year)^2) + sex_br + race_white + 
                    race_black + ethnicity_hisp + scale(income_resid) +
                    (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long, family = binomial, nAGQ = 0)


SA_mod_2 <- glmer(SA_y ~ LGBT_inclusive + dim_yesno_q3 + scale(reshist_state_so_factor) + scale(age_year) + (scale(age_year)^2) + sex_br + race_white + 
                    race_black + ethnicity_hisp + scale(income_resid) +
                    (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long, family = binomial, nAGQ = 0)


SA_mod_3 <- glmer(SA_y ~ LGBT_inclusive + dim_yesno_q3 + scale(reshist_state_so_factor) + scale(age_year) + (scale(age_year)^2) + sex_br + race_white +
                    race_black + ethnicity_hisp + scale(income_resid) +
                    dim_yesno_q1 + dim_yesno_q2 + dim_yesno_q4 + cybb_phenx_harm + bully_vic + reshist_addr1_adi_perc +
                    (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long, family = binomial, nAGQ = 0)

SA_mod_4 <- glmer(SA_y ~ LGBT_inclusive + dim_yesno_q3 + scale(reshist_state_so_factor) + scale(age_year) + (scale(age_year)^2) + sex_br + race_white +
                    race_black + ethnicity_hisp + scale(income_resid) +
                    dim_yesno_q1 + dim_yesno_q2 + dim_yesno_q4 + cybb_phenx_harm + bully_vic +
                    dim_yesno_q3*LGBT_inclusive + dim_yesno_q3*scale(reshist_state_so_factor) + scale(reshist_state_so_factor)*LGBT_inclusive + reshist_addr1_adi_perc +
                    (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long, family = binomial, nAGQ = 0)


SA_comb <- tab_model(SA_mod_1, SA_mod_2, SA_mod_3, SA_mod_4, show.intercept = F)
SA_comb
```

# SENSITIVITY ANALYSIS
## CBCL
```{r}
cbcl_mod_1 <- lmer(cbcl_scr_syn_totprob_t ~ LGBT_inclusive + scale(age_year) + (scale(age_year)^2) + sex_br + race_white + 
                    race_black + ethnicity_hisp + scale(income_resid) +
                    (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long)

cbcl_mod_2 <- lmer(cbcl_scr_syn_totprob_t ~ LGBT_inclusive + dim_yesno_q3 + scale(reshist_state_so_factor) + scale(age_year) + (scale(age_year)^2) + sex_br + race_white + 
                    race_black + ethnicity_hisp + scale(income_resid) +
                    (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long)

cbcl_mod_3 <- lmer(cbcl_scr_syn_totprob_t ~ LGBT_inclusive + dim_yesno_q3 + scale(reshist_state_so_factor) + scale(age_year) + (scale(age_year)^2) + sex_br + race_white +
                    race_black + ethnicity_hisp + scale(income_resid) +
                    dim_yesno_q1 + dim_yesno_q2 + dim_yesno_q4 + cybb_phenx_harm + bully_vic + reshist_addr1_adi_perc +
                                           (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long,
                  control=lmerControl(check.nobs.vs.nlev = "ignore",
                                      check.nobs.vs.rankZ = "ignore",
                                      check.nobs.vs.nRE="ignore",
                                      optimizer = "bobyqa", optCtrl = list(maxfun = 2e5)))

cbcl_mod_4 <- lmer(cbcl_scr_syn_totprob_t ~ LGBT_inclusive + dim_yesno_q3 + scale(reshist_state_so_factor) + scale(age_year) + (scale(age_year)^2) + sex_br + race_white +
                    race_black + ethnicity_hisp + scale(income_resid) +
                    dim_yesno_q1 + dim_yesno_q2 + dim_yesno_q4 + cybb_phenx_harm + bully_vic +
                    dim_yesno_q3*LGBT_inclusive + dim_yesno_q3*scale(reshist_state_so_factor) + scale(reshist_state_so_factor)*LGBT_inclusive + reshist_addr1_adi_perc +
                    (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long,
                  control=lmerControl(check.nobs.vs.nlev = "ignore",
                                      check.nobs.vs.rankZ = "ignore",
                                      check.nobs.vs.nRE="ignore",
                                      optimizer = "bobyqa", optCtrl = list(maxfun = 2e5)))


cbcl_comb <- tab_model(cbcl_mod_1, cbcl_mod_2, cbcl_mod_3, cbcl_mod_4, show.intercept = F)
cbcl_comb
```

## Among LGBT only (exclude "maybe" SGM kids)
```{r}
# BPM
bpm_sens_mod_1 <- lmer(bpm_y_scr_totalprob_t ~ LGBT + scale(age_year) + (scale(age_year)^2) + sex_br + race_white + 
                    race_black + ethnicity_hisp + scale(income_resid) +
                    (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long)

bpm_sens_mod_2 <- lmer(bpm_y_scr_totalprob_t ~ LGBT + dim_yesno_q3 + scale(reshist_state_so_factor) + scale(age_year) + (scale(age_year)^2) + sex_br + race_white + 
                    race_black + ethnicity_hisp + scale(income_resid) +
                    (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long)

bpm_sens_mod_3 <- lmer(bpm_y_scr_totalprob_t ~ LGBT + dim_yesno_q3 + scale(reshist_state_so_factor) + scale(age_year) + (scale(age_year)^2) + sex_br + race_white +
                    race_black + ethnicity_hisp + scale(income_resid) +
                    dim_yesno_q1 + dim_yesno_q2 + dim_yesno_q4 + cybb_phenx_harm + bully_vic + reshist_addr1_adi_perc +
                    (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long,
                  control=lmerControl(check.nobs.vs.nlev = "ignore",
                                      check.nobs.vs.rankZ = "ignore",
                                      check.nobs.vs.nRE="ignore",
                                      optimizer = "bobyqa", optCtrl = list(maxfun = 2e5)))

bpm_sens_mod_4 <- lmer(bpm_y_scr_totalprob_t ~ LGBT + dim_yesno_q3 + scale(reshist_state_so_factor) + scale(age_year) + (scale(age_year)^2) + sex_br + race_white +
                    race_black + ethnicity_hisp + scale(income_resid) +
                    dim_yesno_q1 + dim_yesno_q2 + dim_yesno_q4 + cybb_phenx_harm + bully_vic +
                    dim_yesno_q3*LGBT + dim_yesno_q3*scale(reshist_state_so_factor) + scale(reshist_state_so_factor)*LGBT + reshist_addr1_adi_perc +
                    (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long,
                  control=lmerControl(check.nobs.vs.nlev = "ignore",
                                      check.nobs.vs.rankZ = "ignore",
                                      check.nobs.vs.nRE="ignore",
                                      optimizer = "bobyqa", optCtrl = list(maxfun = 2e5)))

bpm_sens_comb <- tab_model(bpm_sens_mod_1, bpm_sens_mod_2, bpm_sens_mod_3, bpm_sens_mod_4, show.intercept = F) #
bpm_sens_comb
```

```{r}
# SI
SI_sens_mod_1 <- glmer(SI_y ~ LGBT + scale(age_year) + (scale(age_year)^2) + sex_br + race_white + 
                    race_black + ethnicity_hisp + scale(income_resid) +
                    (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long, family = binomial, nAGQ = 0)


SI_sens_mod_2 <- glmer(SI_y ~ LGBT + dim_yesno_q3 + scale(reshist_state_so_factor) + scale(age_year) + (scale(age_year)^2) + sex_br + race_white + 
                    race_black + ethnicity_hisp + scale(income_resid) +
                    (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long, family = binomial, nAGQ = 0)


SI_sens_mod_3 <- glmer(SI_y ~ LGBT + dim_yesno_q3 + scale(reshist_state_so_factor) + scale(age_year) + (scale(age_year)^2) + sex_br + race_white +
                    race_black + ethnicity_hisp + scale(income_resid) +
                    dim_yesno_q1 + dim_yesno_q2 + dim_yesno_q4 + cybb_phenx_harm + bully_vic + reshist_addr1_adi_perc +
                    (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long, family = binomial, nAGQ = 0)

SI_sens_mod_4 <- glmer(SI_y ~ LGBT + dim_yesno_q3 + scale(reshist_state_so_factor) + scale(age_year) + (scale(age_year)^2) + sex_br + race_white +
                    race_black + ethnicity_hisp + scale(income_resid) +
                    dim_yesno_q1 + dim_yesno_q2 + dim_yesno_q4 + cybb_phenx_harm + bully_vic +
                    dim_yesno_q3*LGBT + dim_yesno_q3*scale(reshist_state_so_factor) + scale(reshist_state_so_factor)*LGBT + reshist_addr1_adi_perc +
                    (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long, family = binomial, nAGQ = 0)


SI_sens_comb <- tab_model(SI_sens_mod_1, SI_sens_mod_2, SI_sens_mod_3, SI_sens_mod_4, show.intercept = F)
SI_sens_comb
```

```{r}
# SA
SA_sens_mod_1 <- glmer(SA_y ~ LGBT + scale(age_year) + (scale(age_year)^2) + sex_br + race_white + 
                    race_black + ethnicity_hisp + scale(income_resid) +
                    (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long, family = binomial, nAGQ = 0)


SA_sens_mod_2 <- glmer(SA_y ~ LGBT + dim_yesno_q3 + scale(reshist_state_so_factor) + scale(age_year) + (scale(age_year)^2) + sex_br + race_white + 
                    race_black + ethnicity_hisp + scale(income_resid) +
                    (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long, family = binomial, nAGQ = 0)


SA_sens_mod_3 <- glmer(SA_y ~ LGBT + dim_yesno_q3 + scale(reshist_state_so_factor) + scale(age_year) + (scale(age_year)^2) + sex_br + race_white +
                    race_black + ethnicity_hisp + scale(income_resid) +
                    dim_yesno_q1 + dim_yesno_q2 + dim_yesno_q4 + cybb_phenx_harm + bully_vic + reshist_addr1_adi_perc +
                    (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long, family = binomial, nAGQ = 0)

SA_sens_mod_4 <- glmer(SA_y ~ LGBT + dim_yesno_q3 + scale(reshist_state_so_factor) + scale(age_year) + (scale(age_year)^2) + sex_br + race_white +
                    race_black + ethnicity_hisp + scale(income_resid) +
                    dim_yesno_q1 + dim_yesno_q2 + dim_yesno_q4 + cybb_phenx_harm + bully_vic +
                    dim_yesno_q3*LGBT + dim_yesno_q3*scale(reshist_state_so_factor) + scale(reshist_state_so_factor)*LGBT + reshist_addr1_adi_perc +
                    (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long, family = binomial, nAGQ = 0)


SA_sens_comb <- tab_model(SA_sens_mod_1, SA_sens_mod_2, SA_sens_mod_3, SA_sens_mod_4, show.intercept = F)
SA_sens_comb
```

```{r}
# CBCL
cbcl_sens_mod_1 <- lmer(cbcl_scr_syn_totprob_t ~ LGBT + scale(age_year) + (scale(age_year)^2) + sex_br + race_white + 
                     race_black + ethnicity_hisp + scale(income_resid) +
                     (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long)

cbcl_sens_mod_2 <- lmer(cbcl_scr_syn_totprob_t ~ LGBT + dim_yesno_q3 + scale(reshist_state_so_factor) + scale(age_year) + (scale(age_year)^2) + sex_br + race_white + 
                     race_black + ethnicity_hisp + scale(income_resid) +
                     (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long)

cbcl_sens_mod_3 <- lmer(cbcl_scr_syn_totprob_t ~ LGBT + dim_yesno_q3 + scale(reshist_state_so_factor) + scale(age_year) + (scale(age_year)^2) + sex_br + race_white +
                     race_black + ethnicity_hisp + scale(income_resid) +
                     dim_yesno_q1 + dim_yesno_q2 + dim_yesno_q4 + cybb_phenx_harm + bully_vic + reshist_addr1_adi_perc +
                     (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long,
                   control=lmerControl(check.nobs.vs.nlev = "ignore",
                                       check.nobs.vs.rankZ = "ignore",
                                       check.nobs.vs.nRE="ignore",
                                       optimizer = "bobyqa", optCtrl = list(maxfun = 2e5)))

cbcl_sens_mod_4 <- lmer(cbcl_scr_syn_totprob_t ~ LGBT + dim_yesno_q3 + scale(reshist_state_so_factor) + scale(age_year) + (scale(age_year)^2) + sex_br + race_white +
                     race_black + ethnicity_hisp + scale(income_resid) +
                     dim_yesno_q1 + dim_yesno_q2 + dim_yesno_q4 + cybb_phenx_harm + bully_vic +
                     dim_yesno_q3*LGBT + dim_yesno_q3*scale(reshist_state_so_factor) + scale(reshist_state_so_factor)*LGBT + reshist_addr1_adi_perc +
                     (1 | site_id_l_br/rel_family_id/src_subject_id), data = dataset_long,
                   control=lmerControl(check.nobs.vs.nlev = "ignore",
                                       check.nobs.vs.rankZ = "ignore",
                                       check.nobs.vs.nRE="ignore",
                                       optimizer = "bobyqa", optCtrl = list(maxfun = 2e5)))


cbcl_sens_comb <- tab_model(cbcl_sens_mod_1, cbcl_sens_mod_2, cbcl_sens_mod_3, cbcl_sens_mod_4, show.intercept = F)
cbcl_sens_comb
```

